portfolio_app/config/routes.rb
Rails.application.routes.draw do
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "students#index"
end

portfolio_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

portfolio_app/app/models/student.rb
class Student < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :major, presence: true
    validates :graduation_date, presence: true
    validates :school_email, presence: true
    validates :school_email, uniqueness: true
    validate :school_email_format
    has_one_attached :profile_picture, dependent: :purge_later
    validate :acceptable_image
 
    def school_email_format
        unless school_email =~ /\A[\w+\-.]+@msudenver\.edu\z/i
            errors.add(:school_email, "must be an @msudenver.edu email address")
        end
    end
 
    def acceptable_image
        return unless profile_picture.attached?
 
        unless profile_picture.blob.byte_size <= 1.megabyte
            errors.add(:profile_picture, "is too big")
        end
 
        acceptable_types = ["image/jpeg", "image/png"]
        unless acceptable_types.include?(profile_picture.content_type)
            errors.add(:profile_picture, "must be a JPEG or PNG")
        end
 
  end
    VALID_MAJORS = ["Computer Engineering BS", "Computer Information Systems BS",
    "Computer Science BS", "Cybersecurity Major", "Data Science and Machine Learning Major"]

    validates :major, inclusion: { in: VALID_MAJORS, message: "%{value} is not a valid major" }
 end
 

portfolio_app/app/models/user.rb
class User < ApplicationRecord
end

portfolio_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

portfolio_app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_path, status: :see_other, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :school_email, :major, :graduation_date, :profile_picture)
    end
 
end

portfolio_app/app/helpers/application_helper.rb
module ApplicationHelper
end

portfolio_app/app/helpers/students_helper.rb
module StudentsHelper
end

portfolio_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>YourApp</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <!-- Include Bootstrap CSS via CDN -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" defer></script>
   <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
   <%= javascript_include_tag "application", type: "module", "data-turbo-track": "reload", defer: true %>
 </head>

 <body>

   <%= yield %>
 </body>
</html>

portfolio_app/app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :school_email, style: "display: block" %>
    <%= form.text_field :school_email %>
  </div>

  <div>
    <%= form.label :major, style: "display: block" %>
    <%= form.text_field :major %>
  </div>

  <div>
    <%= form.label :minor, style: "display: block" %>
    <%= form.text_field :minor %>
  </div>

  <div>
    <%= form.label :graduation_date, style: "display: block" %>
    <%= form.date_field :graduation_date %>
  </div>
  
  <div>
    <%= form.label :profile_picture, style: "display: block" %>
    <%= form.file_field :profile_picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

portfolio_app/app/views/students/_search_form.html.erb
<%= form_with(url: students_path, method: :get, local: true, class: "form-inline") do |form| %>
    <div>
      <%= form.label :major, "Select Major", class: "form-label" %>
      <%= form.select :major, options_for_select(Student::VALID_MAJORS), { prompt: "Any Major" }, name: 'search[major]', class: "form-control" %>
    </div>
   
    <div>
      <%= form.submit "Search", class: "btn btn-primary" %>
    </div>
<% end %>

portfolio_app/app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>School email:</strong>
    <%= student.school_email %>
  </p>

  <p>
    <strong>Major:</strong>
    <%= student.major %>
  </p>

  <p>
    <strong>Minor:</strong>
    <%= student.minor %>
  </p>

  <p>
    <strong>Graduation date:</strong>
    <%= student.graduation_date %>
  </p>
  <p>
    <% if student.profile_picture.attached? %>
      <%= image_tag student.profile_picture.variant(resize_to_limit: [150, nil])%>
    <% else %>
      <%= image_tag 'default-profile-picture.png', size: "150x150" %>
    <% end %>
  </p>


</div>

portfolio_app/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

portfolio_app/app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

portfolio_app/app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

portfolio_app/app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>